// VoltFlow — EcoFlow Product Catalog
// Prices in cents (Stripe format). displayPrice in dollars.

const PRODUCTS = [
  {
    id: 'river3plus',
    name: 'RIVER 3 Plus',
    brand: 'EcoFlow',
    tagline: 'Portable & expandable off-grid power',
    description: 'Lightweight and powerful, the RIVER 3 Plus is perfect for camping, road trips, and emergency backup. Expandable up to 858Wh with an add-on battery.',
    price: 26900,
    displayPrice: 269,
    category: 'portable',
    specs: { capacity: '286Wh', output: '600W', weight: '7.28 lb', recharge: '1.3 hrs (AC)' },
    image: 'https://us.ecoflow.com/cdn/shop/files/ecoflow-us-ecoflow-river-3-plus-portable-power-station-standalone-36158995398729.png?v=1764216261',
    badge: null,
    inStock: true,
  },
  {
    id: 'delta3plus',
    name: 'DELTA 3 Plus',
    brand: 'EcoFlow',
    tagline: 'Expandable 1–5kWh for home & outdoors',
    description: 'A versatile workhorse that scales from 1kWh to 5kWh with add-on batteries. Handles most home appliances and charges fast.',
    price: 64900,
    displayPrice: 649,
    category: 'portable',
    specs: { capacity: '1–5kWh', output: '1800W', weight: '22.5 lb', recharge: '50 min (AC)' },
    image: 'https://us.ecoflow.com/cdn/shop/files/ecoflow-us-ecoflow-delta-3-plus-portable-power-station-standalone-delta-3-plus-1179495741.png?v=1755573843',
    badge: 'Best Seller',
    inStock: true,
  },
  {
    id: 'delta3maxplus',
    name: 'DELTA 3 Max Plus',
    brand: 'EcoFlow',
    tagline: 'High-capacity portable power, 3000W output',
    description: 'The DELTA 3 Max Plus delivers 3000W continuous output and 2048Wh capacity — enough to run a full home setup for hours.',
    price: 104900,
    displayPrice: 1049,
    category: 'portable',
    specs: { capacity: '2048Wh', output: '3000W', weight: '48.5 lb', recharge: '43 min (AC)' },
    image: 'https://cdn.shopify.com/s/files/1/1996/9707/files/ecoflow-ecoflow-delta-3-max-series-portable-power-station-2048wh-d3m-series-delta-3-max-plus-2048wh-delta-3-max-plus-portable-power-station-2048wh-1209244376.png?v=1769742118',
    badge: null,
    inStock: true,
  },
  {
    id: 'deltapro3',
    name: 'DELTA Pro 3',
    brand: 'EcoFlow',
    tagline: 'Whole-home backup, expandable to 48kWh',
    description: 'Professional-grade power for your entire home. Expandable from 4kWh to 48kWh and capable of running central AC with X-Boost technology.',
    price: 199900,
    displayPrice: 1999,
    category: 'home',
    specs: { capacity: '4–48kWh', output: '4000W (6000W X-Boost)', weight: '99.2 lb', recharge: '2.5 hrs (AC)' },
    image: 'https://us.ecoflow.com/cdn/shop/files/ecoflow-ecoflow-delta-pro-3-portable-power-station-ul9540-certificated-dp3-delta-pro-3-1179495742.png?v=1762761450',
    badge: 'Popular',
    inStock: true,
  },
  {
    id: 'deltaproultra',
    name: 'DELTA Pro Ultra',
    brand: 'EcoFlow',
    tagline: 'UL-certified whole-home backup power',
    description: 'The most advanced home backup system from EcoFlow. UL1973 and UL9540 certified, 12ms auto-switchover, and expandable to 90kWh.',
    price: 409900,
    displayPrice: 4099,
    category: 'home',
    specs: { capacity: '6–90kWh', output: '7200W', weight: 'Requires installation', recharge: 'Grid + Solar' },
    image: 'https://us.ecoflow.com/cdn/shop/files/ecoflow-ecoflow-delta-pro-ultra-whole-home-backup-power-ul-9540-certificated-dpu-bundle-delta-pro-ultra-1-x-inverter-1-x-battery-1179495744.png?v=1767511531',
    badge: 'Premium',
    inStock: true,
  },
  {
    id: 'glacier-classic',
    name: 'GLACIER Classic',
    brand: 'EcoFlow',
    tagline: '55L portable fridge/freezer, 43hrs off-grid',
    description: 'Keep food and drinks cold anywhere for up to 43 hours off-grid. Dual-zone cooling with app control, compatible with all EcoFlow power stations.',
    price: 99900,
    displayPrice: 999,
    category: 'smart-living',
    specs: { capacity: '55L', output: 'Cooling/Freezing', weight: '48.5 lb', recharge: 'Plug-in battery' },
    image: 'https://cdn.shopify.com/s/files/1/1996/9707/files/ecoflow-us-ecoflow-glacier-classic-portable-fridge-freezer-glacier-classic-1176515759.png?v=1766569759',
    badge: null,
    inStock: true,
  },
];

if (typeof module !== 'undefined') module.exports = { PRODUCTS };
